### ISSUE TITLE
It can't work when I use remote proxy. Please kindly help look at it.

### ISSUE THREAD

**Issue by jay763190097** [brozeph/simple-socks#48]
test in local env
![image](https://user-images.githubusercontent.com/16317178/139275793-7bd3aedc-07f7-4e81-8d26-96fd044ded0f.png)
test in my computer
![image](https://user-images.githubusercontent.com/16317178/139276541-12085177-5a82-4607-a7f1-88b95df5fc4b.png)

this is the log
```
[root@iZj6caq81rcy1s8vj7cxx0Z simple-proxy]# node ./createServer.js 

------------------------------------------------------------
new socks5 client from ::ffff:127.0.0.1:37772
connected to remote server at 142.250.199.68:443
4304
4304
642
642
31
31
4855
4855
11306
11306
client ::ffff:127.0.0.1:37772 request has disconnected from remote server at 142.250.199.68:443 with no error

------------------------------------------------------------
new socks5 client from ::ffff:183.237.146.203:46706

unable to connect to remote server
Error: connect ETIMEDOUT 172.217.17.36:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.17.36',
  port: 443,
  addr: '172.217.17.36',
  atyp: 1
}
socket closed with code 3
{
  ver: 5,
  cmd: 1,
  rsv: 0,
  atyp: 1,
  requestBuffer: <Buffer 05 03 00 01 ac d9 11 24 01 bb>,
  dst: { addr: '172.217.17.36', port: 443 },
  addr: { buf: <Buffer ac d9 11 24> }
}
```

I don't why the ip address is 172.217.17.36, can we do more enhancement?

**Comment by jay763190097** [comment]
I guess it's the dns issue, Can you give some suggestions?

**Comment by brozeph** [comment]
@jay763190097, to verify it is a DNS issue, can you try using `--resolve` with curl to pin the address? (<https://stackoverflow.com/questions/38086045/use-curl-resolve-with-http-proxy>)

**Comment by brozeph** [comment]
Closing due to time
